<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FIC-I7KL93" failures="1" tests="9" name="com.evaa.chatbot.RescheduleAppointmentTest" time="364.860" errors="1" timestamp="2025-06-11T15:39:03 IST" skipped="3">
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="Enable_Reschedule_from_admin" time="19.800"/>
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="Test_Reschedule_an_appointment_for_new_user" time="42.820">
    <failure message="expected [upcoming Appointment ] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [upcoming Appointment ] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.evaa.chatbot.RescheduleAppointmentTest.Test_Reschedule_an_appointment_for_new_user(RescheduleAppointmentTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Test_Reschedule_an_appointment_for_new_user -->
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="Test_Reschedule_an_appointment_for_new_user" time="28.895">
    <skipped/>
  </testcase> <!-- Test_Reschedule_an_appointment_for_new_user -->
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="RescheduleAppointment" time="70.300">
    <error message="Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on WINDOWS (5d58da7a7ff3d6f3c27d4c162a6bc007)] -&gt; xpath: (//div[@class=&#039;pr-4 pl-4&#039;]//div[@class=&#039;v-select__slot&#039;])[1]] (tried for 50 second(s) with 500 milliseconds interval)
Build info: version: &#039;4.1.4&#039;, revision: &#039;535d840ee2&#039;
System info: host: &#039;FIC-I7KL93&#039;, ip: &#039;172.20.10.13&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.6&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 137.0.7151.69, chrome: {chromedriverVersion: 137.0.7151.70 (dfa4dc56b2ab..., userDataDir: C:\Users\Satish_G\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55999}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55999/devtoo..., se:cdpVersion: 137.0.7151.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 5d58da7a7ff3d6f3c27d4c162a6bc007" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on WINDOWS (5d58da7a7ff3d6f3c27d4c162a6bc007)] -> xpath: (//div[@class='pr-4 pl-4']//div[@class='v-select__slot'])[1]] (tried for 50 second(s) with 500 milliseconds interval)
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'FIC-I7KL93', ip: '172.20.10.13', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 137.0.7151.69, chrome: {chromedriverVersion: 137.0.7151.70 (dfa4dc56b2ab..., userDataDir: C:\Users\Satish_G\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55999}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55999/devtoo..., se:cdpVersion: 137.0.7151.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 5d58da7a7ff3d6f3c27d4c162a6bc007
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at com.evaa.chatbot.pom.BookAppointment.waitForElementVisible(BookAppointment.java:25)
at com.evaa.chatbot.pom.BookAppointment.openLocationDropdown(BookAppointment.java:274)
at com.evaa.chatbot.RescheduleAppointmentTest.fillAppointmentDetails(RescheduleAppointmentTest.java:164)
at com.evaa.chatbot.RescheduleAppointmentTest.RescheduleAppointment(RescheduleAppointmentTest.java:117)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- RescheduleAppointment -->
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="RescheduleAppointment" time="68.498">
    <skipped/>
  </testcase> <!-- RescheduleAppointment -->
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="bookAppointment" time="41.388"/>
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="Disable_Reschedule_from_admin" time="22.568"/>
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="TestRescheduleAppointmentDisabled" time="12.804"/>
  <system-out/>
  <testcase classname="com.evaa.chatbot.RescheduleAppointmentTest" name="TestRescheduleAppointmentDisabled" time="57.787">
    <skipped/>
  </testcase> <!-- TestRescheduleAppointmentDisabled -->
  <system-out/>
</testsuite> <!-- com.evaa.chatbot.RescheduleAppointmentTest -->
